import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen bg-white text-slate-900 dark:bg-slate-900 dark:text-slate-50">
          {/* Sidebar */}
          <div className="w-56 h-full">
            <Sidebar />
          </div>

          {/* Main content area */}
          <div className="flex-1 p-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
